title: aDOMonitions
description: Styled admonition callouts, converted on page load.
remote_theme: carlosperate/jekyll-theme-rtd

# Theme options
logo: "img/logo-wordmark.png"
favicon: "img/favicon.ico"
nav_external_links:
  - section: Demos
  - title: Live demo page
    url: "https://carlosperate.github.io/aDOMonitions/demo.html"
